### ISSUE TITLE
Source of this data

### ISSUE THREAD

**Issue by rbhatia46** [justinelliotmeyers/India_Locality_Polygons#1]
Hi,
Can you please let me know the source of this data and how accurate is this data, also, does it cover tier-2 and tier-3 cities in India? If not, any idea where can I find that?

Thanks in Advance,
Regards,
Rahul

**Comment by justinelliotmeyers** [comment]
source of this data: Colleague in India provided it to me.
how accurate is this data: No idea - you would have t do your own analysis to your own standards.
does it cover tier-2 and tier-3 cities in India: No idea - you would have t do your own analysis to your own standards.
where can I find that - not certain - I've never seen a list of these.

Sorry I cannot help - I just share raw data.
